# Generated by Django 3.2.20 on 2023-07-29 22:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_name', models.CharField(max_length=25)),
                ('booking_date', models.DateField()),
                ('course', models.IntegerField(choices=[(1, 'Indian Classical'), (2, '\tIndian Bollywood'), (3, 'Yoga Dance'), (4, 'Street Dance'), (5, 'Ballet Dance'), (6, 'Zumba dance')])),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['booking_date'],
            },
        ),
    ]
