# Generated by Django 3.2.20 on 2023-08-01 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_booking_booking_datedate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='booking_datedate',
            new_name='booking_date',
        ),
    ]
