# Generated by Django 3.2.20 on 2023-08-01 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_rename_booking_datedate_booking_booking_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='booking_date',
        ),
        migrations.AddField(
            model_name='booking',
            name='personal_number',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
