# Generated by Django 3.2.20 on 2023-08-01 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_auto_20230801_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='personal_number',
            field=models.CharField(max_length=10),
        ),
    ]
