# Generated by Django 3.2.20 on 2023-08-02 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_alter_booking_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='Indian_clasical',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
