# Generated by Django 3.2.20 on 2023-08-02 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_booking_indian_clasical'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='Indian_clasical',
        ),
    ]
