# Generated by Django 3.2.20 on 2023-08-11 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0012_booking_booked_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='username',
        ),
        migrations.AlterField(
            model_name='booking',
            name='booked_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='Bookcourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_name', models.CharField(max_length=25)),
                ('booked_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('dob', models.DateField(default=False, max_length=8)),
                ('spring_term', models.BooleanField(default=False)),
                ('autumn_term', models.BooleanField(default=False)),
                ('course', models.CharField(choices=[('Indian Classical', 'Indian Classical'), ('Indian Bollywood', 'Indian Bollywood'), ('Yoga Dance', 'Yoga Dance'), ('Street Dance', 'Street Dance'), ('Ballet Dance', 'Ballet Dance'), ('Zumba dance', 'Zumba dance')], max_length=30)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['booked_date'],
            },
        ),
    ]
