# Generated by Django 3.2.20 on 2023-08-11 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_auto_20230811_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcourse',
            name='days',
            field=models.CharField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=False, max_length=10),
        ),
    ]
