# Generated by Django 3.2.20 on 2023-08-11 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_bookcourse_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookcourse',
            name='days',
        ),
    ]
