# Generated by Django 3.2.20 on 2023-07-28 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyalong', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='updated_on',
        ),
        migrations.AlterField(
            model_name='course',
            name='starting_on',
            field=models.DateField(null=True),
        ),
    ]
