# Generated by Django 3.2.20 on 2023-07-29 09:58

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studyalong', '0003_interest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
