# Generated by Django 3.2.20 on 2023-07-29 10:20

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studyalong', '0004_alter_course_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
