# Generated by Django 3.2.20 on 2023-07-29 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studyalong', '0005_alter_course_featured_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='featured_image',
            new_name='course_image',
        ),
    ]
