# Generated by Django 3.2.20 on 2023-08-13 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studyalong', '0008_rename_place_course_place'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Interest',
        ),
    ]
